version: '3.5'

services:
    dcsa-ebl:
        build:
           .
        ports:
            - 9090:9090
        environment:
            - "SPRING_PROFILES_ACTIVE=local"
        logging:
            options:
                max-file: '10'
                max-size: 200k

    dcsa-test-db:
        container_name: dcsa_db
        environment:
            POSTGRES_PASSWORD: "change_this_password"
        build:
            DCSA-Information-Model/datamodel/
        ports:
            - 5432:5432
