version: '3.5'

services:
    dcsa-ebl:
        build:
           .
        ports:
            - 9090:9090
        environment:
            - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-default}"
        logging:
            options:
                max-file: '10'
                max-size: 200k

    dcsa-test-db:
        container_name: dcsa_db
        environment:
            POSTGRES_PASSWORD: "change_this_password"
        image: postgres:10-alpine
        ports:
            - 5432:5432
        volumes:
          - ./DCSA-Information-Model/datamodel/initdb.d:/docker-entrypoint-initdb.d:ro
          - ./DCSA-Information-Model/datamodel/referencedata.d:/referencedata.d:ro
          - ./DCSA-Information-Model/datamodel/samples.d:/samples.d:ro
