version: '3.5'
services:
    dcsa-ebl:
        build:
           .
        ports:
            - 9090:9090
        logging:
            options:
                max-file: '10'
                max-size: 200k
