name: DCSA-EBL MASTER CI

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: DCSA-EBL
        submodules: recursive

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 17
        cache: 'maven'

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v12
      with:
        repositories: '[{ "id": "github", "name": "DCSA Backend repo", "url": "https://maven.pkg.github.com/dcsaorg/DCSA-Core", "releases": { "enabled": "true" }, "snapshots": { "enabled": "true" } }]'
        servers: '[{ "id": "github", "username": "${{ secrets.DCSA_USER }}", "password": "${{ secrets.DCSA_PACKAGES_PAT }}" }]'

    - name: Fetch backend
      uses: actions/checkout@v2
      with:
        path: DCSA-EBL
        submodules: recursive

    - name: Build eBL API
      run: cd DCSA-EBL && mvn clean -U -B package -Ddcsa.artifacttype=-SNAPSHOT

    - name: Build and run the microservices
      run: cd DCSA-EBL && docker-compose -f docker-compose.yml up -d -V --build

    - name: Fetch Backend Status
      run: |
        sleep 10
        echo "::set-output name=STATUS::$(curl -s http://localhost:9090/v2/actuator/health | jq -r '.status')"
      id: healthcheck

    - name: Confirm microservice status
      if: ${{ steps.healthcheck.outputs.STATUS == 'UP' }}
      run: |
        echo "The DCSA-EBL service is UP."

    - name: Confirm microservice status
      if: ${{ steps.healthcheck.outputs.STATUS != 'UP' }}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('The DCSA-EBL service is down.')

    - name: Run Integration Tests
      run: |
        cd DCSA-EBL && mvn verify -B failsafe:verify -Ddcsa.artifacttype=-SNAPSHOT
